version: '3'
services:
  backend:
    container_name: backend
    build: ./Back-end
    ports:
      - "8090:8090"
  frontend:
    container_name: frontend
    build: ./Front-end
    ports:
      - "80:80"
    depends_on:
      - backend